//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NUWM_Schedule_Bot.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NUWM_Schedule_Bot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на АУТПпз-21і,АУТПпз-31і,ОАп-41з,ОАп-51з,ОАп-61з,ОАпі-1з,ОАпі-2з,ЗВКп-11інт,ЗВКп-21інт,ЗВКп-31ін,ЗВКп-61з,ТГВп-11інт,ТГВп-21інт,ТГВп-31інт,ГМп-61з,ГМпі-11з,ГМпі-21з,ГМпі-31з,ТГПп-61з,Мп-51.
        /// </summary>
        internal static string faculty1019 {
            get {
                return ResourceManager.GetString("faculty1019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на АУТПв-61,АУТПз-3з,АУТПз-4з,АУТПзі-31і,ОАв-31,ОАв-41,ОАв-51,ОАв-51інт,ОАв-61з,МБз-3з,МБз-4з,МБз-5з,ЕКОв-31,ЕКОв-41,ЕКОв-51,ЕКОв-61з,ЗВКв-61,ЗВКз-31з,ЗВКз-41з,ЗВКз-51з,ГМз-61з.
        /// </summary>
        internal static string faculty1022 {
            get {
                return ResourceManager.GetString("faculty1022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ЗВКс-51з,ЗВКс-61з,ЗВКсі-31,ЗВКсі-41,ЗВКсі-51,ГМс-41з,ГМс-51з,ГМс-61з,ГМсз-41інт,ГМсз-51інт,ЕКОс-51і,ЕКОс-51із,ЕКОс-61з.
        /// </summary>
        internal static string faculty1023 {
            get {
                return ResourceManager.GetString("faculty1023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аспіранти,Докторанти,Здобувачі,ДФ-1,ДФ-2,ДФ-3.
        /// </summary>
        internal static string faculty1024 {
            get {
                return ResourceManager.GetString("faculty1024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ЛГ(нсі)-21,ЛГ(нсі)-22,ЛГ(нсі)-31,ЛГ(нсі)-32,ЛГ(нсі)-41,ЛГ(нсі)-42.
        /// </summary>
        internal static string faculty1060 {
            get {
                return ResourceManager.GetString("faculty1060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПД-51,ПД-51з,ПРз-11,ПРз-21,ПРз-31,ПРз-31інт,ПРз-41,ПРз-41інт,ПРз-42інт,ПРз-51м,ПРз-61м,ПР-21інт,ПР-11,ПР-12,ПР-13,ПР-21,ПР-22,ПР-23,ПР-31,ПР-32,ПР-41,ПР-42,ПР-51,ПР-52,ПР-61,ПР-62.
        /// </summary>
        internal static string faculty1064 {
            get {
                return ResourceManager.GetString("faculty1064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ФТЕ(PTE)-5,ФТЕ-11,ФТЕ-11інт,ФТЕ-12,ФТЕ-21,ФТЕ-21інт,ФТЕ-31,ФТЕ-51м,ФТЕ-61м,ФТЕз-21,ФТЕз-21інт,ФТЕз-31,ФТЕз-41,ФТЕм-61з,ФТЕм-71з,ФР-41,ФР-42.
        /// </summary>
        internal static string faculty1066 {
            get {
                return ResourceManager.GetString("faculty1066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ВИРОБ.1,ВИРОБ.2,ВИРОБ.3,ВИРОБ.4,ВИРОБ.5.
        /// </summary>
        internal static string faculty1068 {
            get {
                return ResourceManager.GetString("faculty1068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ЗБ-1.
        /// </summary>
        internal static string faculty1069 {
            get {
                return ResourceManager.GetString("faculty1069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПВА-1,ПВА-2,ПВА-3,ПВФ-1,МЕіноз-21,Ін-11з,Ін-21з,Ін-31з,Ін-41з,Ін-51з,Ін-61з,Ін-11,Ін-21,Ін-31,Ін-41,Ін-51.
        /// </summary>
        internal static string faculty1070 {
            get {
                return ResourceManager.GetString("faculty1070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на АГР-11,АГР-11інт,АГР-21,АГР-21інт,АГР-31,АГР-41,АГР-51м,АГР-61м,АГРз-11,АГРз-11інт,АГРз-21,АГРз-21інт,АГРз-31,АГРз-41,АГРз-61м,АГРз-71м,АГРм-52,АГРм-62,АХГз-51,ВБА-11,ВБА-21,ВБА-31,ВБА-41,ВБА-51м,ВБА-61м,ВБАз-11,ВБАз-21,ВБАз-31,ВБАз-41,ЗВК-31,ЗВК-41,ОВРВГ-62,ГЕО-31,ГЕО-41,ГЗ-11,ГЗ-11інт,ГЗ-12,ГЗ-21,ГЗ-21інт,ГЗ-22,ГЗ-51м,ГЗ-52м,ГЗ-61м,ГЗ-62м,ГЗз-11,ГЗз-11інт,ГЗз-21,ГЗз-31,ГЗз-41,ГЗз-61м,ГЗз-62м,ГЗз-71м,ГЗз-72м,ГКЗз-51,ГРС-11,ГРСз-11,ГІС-31,ГІС-41,ЛГ-51м,ЛГ-61м,ЛГз-61,ЛГз-71,ЕКО-11,ЕКО-11інт,ЕКО-21,ЕКО-21інт, [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string faculty11 {
            get {
                return ResourceManager.GetString("faculty11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на АКІТ-11,АКІТ-21,АКІТ-31,АКІТ-31інт,АКІТ-41,АКІТ-41інт,АКІТз-11ін,АКІТз-21,АКІТз-21і,АКІТз-31,АКІТз-41,АКІТм-51,АУТПз-51,АУТПм-61,АУТПм-61з,АУТПм-71з,ЕЕЕ-11,ЕЕЕ-21,ЕЕЕ-31,ЕЕЕ-31інт,ЕЕЕ-41,ЕЕЕз-11,ЕЕЕз-11інт,ЕЕЕз-21,ЕЕЕз-21інт,ЕЕЕз-31,ЕЕЕз-41,ЕЕЕм-51,ЕЕЕм-61з,ЕЕЕм-71з,ЕЕТ-41інт,ЕЕТз-51,ЕЕТм-61,КНз-11,КНз-11інт,КНз-21,КНз-21інт,КНз-31,КНз-41,КНіноз-21,КІз-11,КІз-21,КІз-21інт,КІз-31,КІз-41,КІз-61м,КІз-71М,ПМз-51,ПМз-61,ІПЗ-11,ІПЗ-11інт,ІПЗ-21,ІПЗ-31,КН-11інт,КН-41інт,КІ-11,КІ-21,КІ-31,КІ-31інт,КІ-41,КІ-41інт,КІ [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string faculty13 {
            get {
                return ResourceManager.GetString("faculty13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на aБВІТ-11інт,БВІТ-21інт,ВГПБ-41,ГБВВ-11,ГБВВ-21,ГТБ-21інт,ГТБ-31,ГТБ-41,ГТБ-53м,ГТБ-63м,ГТБВз-31,ГТБВТз-11,ГТБВТз-11і,ГТБВТз-21,ГТБВТз-21і,ГТБз-31інт,ГТБз-41,ГТБз-51,ГТБзм-61,ГТБзм-71,ВІВТ-51м,ВІВТ-61м,ВІзм-61,ВІзм-71,ВІТ-31,РВОВР-41,Г-11,Г-11інт,Г-21,Г-31,Г-41,ГЕ-11,ГЕ-11інт,ГЕ-21,ГЕ-31,ГЕ-41,ГЕ-51м,ГЕ-61м,ГЕз-11,ГЕз-11інт,ГЕз-31,ГЕз-41,ГЕз-51,ГЕз-61м,ГЕз-71м,Гз-11інт,ГМ-41,ГМз-31інт,ГМз-41,ГМз-51,ГМз-71,ГФ-11,ГФ-21,ГІ-31,ГІ-52м,ГІД-62м,ГІзм-61,ГІзм-71,ТЕ-11,ТЕ-11інт,ТЕ-21,ТЕ-31,ТЕ-41,ТЕз-11,ТЕз-21,ТЕз-31ін [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string faculty4 {
            get {
                return ResourceManager.GetString("faculty4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на А-41+2інт,АДІА-31,АДіА-11інт,АДіА-51м,АДіА-61м,АДіА41+інт,АДіАз-61м,АДіАз-71м,АМ-11,АМ-11інт,АМ-21,АМ-31+інт,АМ-51м,АМ-61м,АМ-62м,БЦІ-11,БЦІ-12,БЦІ-21,БЦІ-22,БЦІз-11,БЦІз-21,ЕЕБ-51м,МБГ-41,МБГ-41інт,МБГ-51м,МБГ-61м,МБГ31+інт,МБГз-11інт,ОП41+ЦБ4ін,ПЦБ-11інт,ПЦБ-31,ПЦБ-32,ПЦБ-41,ПЦБ-42інт,ПЦБ-51м,ПЦБ-52м,ПЦБ-61зм,ПЦБ-61м,ПЦБ-62м,ПЦБ-71зм,ПЦБз-11інт,ПЦБз-21інт,ПЦБз-31,ПЦБз-31інт,ПЦБз-41,ПЦБз-51,ТБК-31+інт,ТБК-41інт,ТБК-51м,ТБК-61м,ЦБ-11,ЦБ-21,ЦБ-31+11ін,ЦБ-51м,ЦБ-61м,ЦБз-21,ЦБз-61м,ЦБз-71м,ВВ-31+інт,ВВ-41+інт, [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string faculty7 {
            get {
                return ResourceManager.GetString("faculty7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на АТ-11,АТ-11інт,АТ-21,АТ-21інт,АТ-31,АТ-41,АТ-51м,АТ-61м,АТз-11,АТз-11інт,АТз-21,АТз-21інт,АТз-31,АТз-31інт,АТз-41,АТз-51,АТз-61м,АТз-71м,АІ-11,АІ-11інт,АІ-21,АІ-21інт,АІз-11інт,АІз-21інт,МБ-11,МБ-21,МБз-11,МБз-21,МБз-31,МБз-41,МБз-51,МБо-21інт,МБо-31,МБо-41,МБоз-21інт,МБоз-31інт,МБоз-61м,МБоз-72м,МБом-51,МБом-61,МБп-11інт,МБп-31,МБп-42,МБпз-11інт,МБпз-31інт,МБпз-61м,МБпз-71м,МБпм-51,МБпм-61,МБсз-61м,МБсз-73м,ГР-11,ГР-11інт,ГР-21,ГР-21інт,ГР-31,ГР-41,ГР-51м,ГР-61м,ГРз-11,ГРз-31,ГРз-41,ГРм-71з,ТТз-11,ТТз-11ін [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string faculty8 {
            get {
                return ResourceManager.GetString("faculty8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на БА-21,БА-31,МАР-11,МАР-11інт,МАР-21,МАР-21інт,МАР-31+інт,МАР-41,МАР-51,МАР-61,МАРз-11,МАРз-11інт,МАРз-21,МАРз-21інт,МАРз-31,МАРз-41,МАРз-51,МАРз-61,МАРз-71,МОіАм-51,МОіАм-61,МОіАм-61з,МОіАм-71з,ОА-21,ОА-31,ОА-41,ОАз-51,ОАм-51,ОАм-61,ОАм-61з,ОАм-71з,ПУА-11,ПУА-21,ПУА-21інт,ПУА-31,ПУА-41,ПУА-51м,ПУА-61м,ПУАз-11інт,ПУАз-21,ПУАз-31,ІБАС-11,УФБз-61,УФБз-71,УФБм-51,УФБм-61,ІТБз-71,ПВШ-51,ПВШ-61,ПВШз-61м,ПВШз-71м,ДСз-21м,ДСз-31,ДІД-11інт,ДІД-21,ДІД-21інт,ДІД-31+інт,ДІД-41,МПДм-61,МС.ДСз-11м,МС.ДСз-21м,ЕК-21,ЕК-21і [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string faculty9 {
            get {
                return ResourceManager.GetString("faculty9", resourceCulture);
            }
        }
    }
}
